### PR TITLE
Fix MSF4J Spring register interceptors as global only

### LINKED ISSUE #470: MSF4J Spring registers all interceptors as global interceptors
**Description:**
MSF4J Spring will register all interceptors as global interceptors. Internally MSF4J Spring will only check if the class is implemented by the appropriate interface [1].

Resource level interceptors will still work. This means that the interceptor will execute globally as well as for the resource. 

[1] https://github.com/wso2/msf4j/blob/master/spring/src/main/java/org/wso2/msf4j/spring/SpringMicroservicesRunner.java#L79-L89

**Suggested Labels:**
Interceptors, Spring, MSF4J

**Suggested Assignees:**
N/A

**Affected Product Version:**
2.4.0 onwards

**OS, DB, other environment details and versions:**    
N/A

**Steps to reproduce:**
N/A

**Related Issues:**
N/A

### PR DESCRIPTION
**Pull request by vidurananayakkara**
## Purpose
Resolves #470 and #433

## Goals
Fix MSF4J Spring registering interceptors as global interceptors only

## Approach
Fixed #470 

## User stories
N/A

## Release note
* Fixed MSF4J Spring registering interceptors as global interceptors only
* Removed checkstate when registering global interceptors since checking it is not necessary.
* Fixed null pointer exception when streaming due to METHOD_PROPERTY_NAME not set
* Added test cases to test interceptor execution in MSF4J spring
* Added a sample to demonstrate MSF4J interceptor with MSF4J spring in fat-jar mode

## Documentation
N/A - This is a bug fix in MSF4J Spring interceptor execution.

## Training
N/A

## Certification
N/A

## Marketing
N/A

## Automation tests
 - Unit tests 
   > Code coverage information
 - Integration tests
   Integration tests are available in `org.wso2.msf4j.spring.SpringInterceptorTest` class

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples
* [MSF4J Interceptors with MSF4J Spring - Fat Jar mode](https://github.com/vidurananayakkara/msf4j/blob/8ed31950cbfce0e9b8995f1467d9ab3bcdd136c1/samples/interceptor/spring-fatjar-interceptor-service/README.md) for using interceptors with MSF4J Spring in fat jar mode

## Related PRs
N/A

## Migrations (if applicable)
N/A

## Test environment
* Oracle JDK 1.8
* Ubuntu 16.04
 
## Learning
N/A

### CODE REVIEW

File: spring/src/main/java/org/wso2/msf4j/spring/MSF4JSpringApplication.java [hunk 1]
```diff
@@ -216,20 +216,21 @@ public void setInitializers(List<ApplicationContextInitializer<?>> initializers)
...
      * @param configurableApplicationContext ConfigurableApplicationContext of running app
-     * @param serviceClass Service class
-     * @param basePath Base path teh servuce get registered
+     * @param serviceClass                   Service class
+     * @param basePath                       Base path to which the service get registered
      */
-    public void addService(ConfigurableApplicationContext configurableApplicationContext, Class serviceClass,
-                           String basePath) {
+    public SpringMicroservicesRunner addService(ConfigurableApplicationContext configurableApplicationContext,
+                                                Class<?> serviceClass, String basePath) {
```
Comment (daneshk) [inline spring/src/main/java/org/wso2/msf4j/spring/MSF4JSpringApplication.java]: Better if we can add new method rather changing the existing one.

Comment (vidurananayakkara) [reply spring/src/main/java/org/wso2/msf4j/spring/MSF4JSpringApplication.java]: This is only a return type change (void -> SpringMicroservicesRunner) and does not break any of the existing implementations.
