### PR TITLE
Change log level of "Added microservice .." logs to debug in server startup

### LINKED ISSUE #525: Change the log level of "Added microservice .." to debug in server startup.
**Description:**
When we deploy microservice, e.g: when we add StockQuoteService. following server log is printed

**[2017-12-19 18:17:10,936]  INFO {org.wso2.msf4j.internal.MicroservicesRegistryImpl} - Added microservice: StockQuoteService-OSGi-bundle**
[2017-12-19 18:17:10,944]  INFO {org.wso2.msf4j.internal.MicroservicesServerSC} - All microservices are available
[2017-12-19 18:17:11,039]  INFO {org.wso2.carbon.kernel.internal.CarbonStartupHandler} - WSO2 Carbon Kernel started in 1.917 sec
[2017-12-19 18:17:11,039]  INFO {org.wso2.transport.http.netty.listener.ServerConnectorBootstrap$HTTPServerConnector} - HTTP(S) Interface starting on host 0.0.0.0 and port 8080

We don't need to print log saying service is added. So we can change the level to debug.

**Suggested Labels:**
task

**Suggested Assignees:**
@daneshk

**Affected Product Version:**
version 2.5.1 and below

**OS, DB, other environment details and versions:**    
environment independent

**Steps to reproduce:**
Start the server. logs will print for each microservice.

**Related Issues:**
N/A

### PR DESCRIPTION
**Pull request by daneshk**
## Purpose
Resolves #525 

## Goals
Change log level of "Added microservice .." logs to debug in server startup
Update license file with correct versions

## Approach
Change the log level to debug

## User stories
N/A

## Release note
N/A

## Documentation
N/A

## Training
N/A

## Certification
N/A. This is small log level changes. no need any changes

## Marketing
N/A

## Automation tests
No need to change add unit test cases.

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples
N/A

## Related PRs
N/A

## Migrations (if applicable)
N/A

## Test environment
Ubuntu 16.06 with jdk 1.8.0.111
 
## Learning
None

### CODE REVIEW

File: core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java [hunk 1]
```diff
@@ -78,13 +78,19 @@ public void addService(Object... service) {
             services.put(svc.getClass().getAnnotation(Path.class).value(), svc);
         }
         updateMetadata();
-        Arrays.stream(service).forEach(svc -> log.info("Added microservice: " + svc));
+        Arrays.stream(service).forEach(svc -> {
```
Comment (this) [inline core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java]: shall we wrap the loop by `log.isDebugEnabled()` 
```java
if(log.isDebugEnabled()) {
   Arrays.stream(service).forEach(svc -> log.debug("Added microservice {}. ", svc));
} 
```

File: core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java [hunk 2]
```diff
@@ -78,13 +78,19 @@ public void addService(Object... service) {
...
+            }
+        });
     }
 
     public void addService(String basePath, Object service) {
         services.put(basePath, service);
         metadata.addMicroserviceMetadata(service, basePath);
-        log.info("Added microservice: " + service);
+        if (log.isDebugEnabled()) {
+            log.debug("Added microservice: " + service);
```
Comment (this) [inline core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java]: No need to check `log.isDebugEnabled()` here. SLF4J internally checks that. 
Also lets use parameterized log message `log.debug("Added microservice {}.", service); 
refer: https://www.slf4j.org/faq.html#logging_performance
