### PR TITLE
Fix issue of can't remove existing services

### LINKED ISSUE #474: MicroservicesRegistryImpl.remove method not working
**Description:**
MicroservicesRegistryImpl.remove() doesn;t remove the srevice.
This is because at 
https://github.com/wso2/msf4j/blob/master/core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java#L95 we pass the service object to remove method instead of service's path value.

**Suggested Labels:**
bug

**Suggested Assignees:**

**Affected Product Version:**
2.4.0

**OS, DB, other environment details and versions:**    

**Steps to reproduce:**
1. Create a MicroservicesRunner and deploy a service
2. Get th registry microservicesRunner.getMsRegistry();
3. Remove the service from the registry
4. Check the registry or invoke the service. Still it exist and work.

**Related Issues:**

### PR DESCRIPTION
**Pull request by thusithathilina**
## Purpose
Resolves #474 

## Goals
This will fix the issue of users can't remove the already added services from the MicroservicesRegistry

## Approach
Instead of directly passing the service object to remove method, we need to get the Path value and use that to remove the existing service.

## User stories
N/A

## Release note
N/A

## Documentation
N/A

## Training
N/A

## Certification
N/A

## Marketing
N/A

## Automation tests
 - Unit tests 
   > Add org.wso2.msf4j.internal.MicroservicesRegistryTest to test the MicroservicesRegistry functionalities
 - Integration tests
   > N/A

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

## Samples
N/A

## Related PRs
N/A

## Migrations (if applicable)
N/A

## Test environment
JDK 1.8.0_40, Ubuntu 14.04
 
## Learning
N/A

### CODE REVIEW

File: core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java [hunk 1]
```diff
@@ -92,8 +92,13 @@ public void addService(String basePath, Object service) {
...
 
     public void removeService(Object service) {
-        services.remove(service);
-        updateMetadata();
+        Path path = service.getClass().getAnnotation(Path.class);
+        if (path != null) {
+            services.remove(path.value());
+            updateMetadata();
+        } else {
+            log.warn("Service removal fail, class '" + service.getClass().getName() + "' doesn't contain a root Path");
```
Comment (this) [inline core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java]: Shall we change this log to `Service removal failed. Microservice class '" + service.getClass().getName() + "' doesn't contain a root Path.`

Comment (DilanUA) [inline core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java]: Better checking for if (path == null) and move corresponding logic to first block for better readability.

File: core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java [hunk 2]
```diff
@@ -92,8 +92,13 @@ public void addService(String basePath, Object service) {
     }
 
     public void removeService(Object service) {
-        services.remove(service);
-        updateMetadata();
+        Path path = service.getClass().getAnnotation(Path.class);
```
Comment (DilanUA) [inline core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java]: Shall we check for null for the service object input and handle it ? Otherwise, that could lead to a possible NPE. WDYT?

File: core/src/test/java/org/wso2/msf4j/internal/MicroservicesRegistryTest.java [hunk 3]
```diff
@@ -0,0 +1,90 @@
...
+import org.wso2.msf4j.service.SecondService;
+
+import java.util.List;
+import java.util.Map;
+import java.util.Optional;
+
+import static org.testng.Assert.assertEquals;
+import static org.testng.Assert.assertFalse;
+import static org.testng.Assert.assertTrue;
+
```
Comment (DilanUA) [inline core/src/test/java/org/wso2/msf4j/internal/MicroservicesRegistryTest.java]: Shall we add class level comments for this?
/**
description...
@since..
*/

File: core/src/test/java/org/wso2/msf4j/internal/MicroservicesRegistryTest.java [hunk 4]
```diff
@@ -0,0 +1,90 @@
...
+    private TestInterceptorDeprecated interceptor2 = new TestInterceptorDeprecated();
+
+    @BeforeClass
+    public void setup() {
+        microservicesRunner.getMsRegistry().addService(service);
+        microservicesRunner.getMsRegistry().addInterceptor(interceptor1, interceptor2);
+        microservicesRunner.getMsRegistry().addExceptionMapper(exceptionMapper1, exceptionMapper2);
+    }
+
+    @Test
```
Comment (DilanUA) [inline core/src/test/java/org/wso2/msf4j/internal/MicroservicesRegistryTest.java]: Shall we add a test group for this (ex: @Test(groups = {"org.wso2.carbon.tomcat.ext.internal"})) and a method comment describing the test case ?

File: core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java [hunk 5]
```diff
@@ -92,8 +92,14 @@ public void addService(String basePath, Object service) {
...
+        if (path != null) {
+            services.remove(path.value());
+            updateMetadata();
+        } else {
+            log.warn("Service removal failed. Microservice class '" + service.getClass().getName() +
+                     "' doesn't contain a root Path.");
```
Comment (DilanUA) [inline core/src/main/java/org/wso2/msf4j/internal/MicroservicesRegistryImpl.java]: Better checking for if (path == null) and move corresponding logic to first block for better readability.
