### PR TITLE
Fix exceptions when executing metrics samples

### LINKED ISSUE #482: Null pointer exception when running metrics sample
**Description:**
Null pointer exception when running metrics sample.

```bash
[msf4j.executor.workerpool-1] ERROR org.wso2.msf4j.analytics.metrics.MetricsInterceptor  - Exception while executing request interceptor class org.wso2.msf4j.analytics.metrics.MetricsInterceptor
java.lang.NullPointerException
at org.wso2.carbon.metrics.core.Metrics.<init>(Metrics.java:78)
at org.wso2.msf4j.analytics.metrics.Metrics.initializeServices(Metrics.java:62)
at org.wso2.msf4j.analytics.metrics.Metrics.getMetricService(Metrics.java:83)
at org.wso2.msf4j.analytics.metrics.MetricsInterceptor.preCall(MetricsInterceptor.java:96)
at org.wso2.msf4j.Interceptor.interceptRequest(Interceptor.java:65)
at org.wso2.msf4j.interceptor.InterceptorExecutor.executeRequestInterceptor(InterceptorExecutor.java:321)
at org.wso2.msf4j.interceptor.InterceptorExecutor.executeGlobalRequestInterceptors(InterceptorExecutor.java:206)
at org.wso2.msf4j.interceptor.InterceptorExecutor.executeGlobalRequestInterceptors(InterceptorExecutor.java:52)
at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:179)
at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:248)
at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$0(MSF4JMessageProcessor.java:160)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
MSF4J 2.4.0 and above

**OS, DB, other environment details and versions:**    
Any

**Steps to reproduce:**

* Run the MSF4J metrics sample
* `curl http://localhost:8080/demo/echo/Hello`

**Related Issues:**
N/A

### PR DESCRIPTION
**Pull request by vidurananayakkara**
## Purpose
Resolves #482 and #489

## Goals
* Fix MSF4J metrics sample throwing null pointer exception
* Fix missing documentation is HTTP monitoring sample

## Release note
* Fix MSF4J metrics sample throwing null pointer exception
* Fix missing documentation is HTTP monitoring sample

## Documentation
Documentation updated with PR

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: samples/metrics/src/main/java/org/wso2/msf4j/sample/metrics/Application.java [hunk 1]
```diff
@@ -17,19 +17,39 @@
...
+
+        // Configuration provider should be set
+        URL resource = Application.class.getClassLoader().getResource("metrics.yaml");
+        if (resource == null) {
+            throw new FileNotFoundException("Metrics configuration resource not found");
+        }
+
+        Path configPath = new File(resource.getFile()).toPath();
+        // We do not need secure vault for this sample and therefore it is null
+        ConfigProvider configProvider = ConfigProviderFactory.getConfigProvider(configPath, null);
```
Comment (daneshk) [inline samples/metrics/src/main/java/org/wso2/msf4j/sample/metrics/Application.java]: Shall we move this logic to org.wso2.msf4j.analytics.metrics.Metrics class. There we can check the configProvider and if not load the default one. and also allow use set configuration file in system property.

**Comment by vidurananayakkara** [comment]
@daneshk Please do review the changes
