### PR TITLE
Fix exceptions when executing metrics samples

### LINKED ISSUE #482: Null pointer exception when running metrics sample
**Description:**
Null pointer exception when running metrics sample.

```bash
[msf4j.executor.workerpool-1] ERROR org.wso2.msf4j.analytics.metrics.MetricsInterceptor  - Exception while executing request interceptor class org.wso2.msf4j.analytics.metrics.MetricsInterceptor
java.lang.NullPointerException
at org.wso2.carbon.metrics.core.Metrics.<init>(Metrics.java:78)
at org.wso2.msf4j.analytics.metrics.Metrics.initializeServices(Metrics.java:62)
at org.wso2.msf4j.analytics.metrics.Metrics.getMetricService(Metrics.java:83)
at org.wso2.msf4j.analytics.metrics.MetricsInterceptor.preCall(MetricsInterceptor.java:96)
at org.wso2.msf4j.Interceptor.interceptRequest(Interceptor.java:65)
at org.wso2.msf4j.interceptor.InterceptorExecutor.executeRequestInterceptor(InterceptorExecutor.java:321)
at org.wso2.msf4j.interceptor.InterceptorExecutor.executeGlobalRequestInterceptors(InterceptorExecutor.java:206)
at org.wso2.msf4j.interceptor.InterceptorExecutor.executeGlobalRequestInterceptors(InterceptorExecutor.java:52)
at org.wso2.msf4j.internal.router.HttpMethodInfo.invokeResource(HttpMethodInfo.java:179)
at org.wso2.msf4j.internal.router.HttpMethodInfo.invoke(HttpMethodInfo.java:143)
at org.wso2.msf4j.internal.MSF4JMessageProcessor.dispatchMethod(MSF4JMessageProcessor.java:248)
at org.wso2.msf4j.internal.MSF4JMessageProcessor.lambda$receive$0(MSF4JMessageProcessor.java:160)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:745)
```

**Suggested Labels:**
Bug

**Suggested Assignees:**
N/A

**Affected Product Version:**
MSF4J 2.4.0 and above

**OS, DB, other environment details and versions:**    
Any

**Steps to reproduce:**

* Run the MSF4J metrics sample
* `curl http://localhost:8080/demo/echo/Hello`

**Related Issues:**
N/A

### PR DESCRIPTION
**Pull request by daneshk**
## Purpose
Resolves #482 and #489

## Goals
- Fix MSF4J metrics sample throwing null pointer exception
- Fix missing documentation is HTTP monitoring sample

## Release note
- Fix MSF4J metrics sample throwing null pointer exception
- Fix missing documentation is HTTP monitoring sample

## Security checks
 - Followed secure coding standards in http://wso2.com/technical-reports/wso2-secure-engineering-guidelines? yes
 - Ran FindSecurityBugs plugin and verified report? yes
 - Confirmed that this PR doesn't commit any keys, passwords, tokens, usernames, or other secrets? yes

### CODE REVIEW

File: analytics/msf4j-analytics/src/main/java/org/wso2/msf4j/analytics/AnalyticUtils.java [hunk 1]
```diff
@@ -0,0 +1,80 @@
...
+            if (deploymentYamlPath == null || deploymentYamlPath.isEmpty()) {
+                logger.info("System property '" + DEPLOYMENT_YAML_SYS_PROPERTY +
+                        "' is not set. Default deployment.yaml file will be used.");
+                deploymentYamlPath = DEPLOYMENT_YAML_FILE;
+                try (InputStream configInputStream = AnalyticUtils.class.getClassLoader()
+                        .getResourceAsStream(DEPLOYMENT_YAML_FILE)) {
+                    if (configInputStream == null) {
+                        throw new RuntimeException("Couldn't find " + deploymentYamlPath);
+                    }
+                    if (Files.notExists(Paths.get(deploymentYamlPath))) {
```
Comment (vidurananayakkara) [inline analytics/msf4j-analytics/src/main/java/org/wso2/msf4j/analytics/AnalyticUtils.java]: IMO I think we should not copy the deployment YAML configuration but rather indicate the developer that we couldn't find the deployment yaml configuration in the given path (of the system property) and therefore is proceeding with the default deployment yaml configuration. WDYT?

Comment (daneshk) [reply analytics/msf4j-analytics/src/main/java/org/wso2/msf4j/analytics/AnalyticUtils.java]: yes, we first check the system property, if that is not exists we are proceeding with the default deplyment yaml configuration.
we have to copy the deployment yaml because we cannot access the resource file when we are running the jar file. So we copy default deployment yaml file to certain location and then it refers in the config provider.
In the MSF4JMessageProcessor class, we have done similar thing. please check[1]
1.https://github.com/wso2/msf4j/blob/master/core/src/main/java/org/wso2/msf4j/internal/MSF4JMessageProcessor.java#L95-L124

Comment (daneshk) [reply analytics/msf4j-analytics/src/main/java/org/wso2/msf4j/analytics/AnalyticUtils.java]: We check the Files.notExists() to avoid copy the configuration each time the application run. configuration should copy only once.
